[merge-tools.idea]
program = "/Users/tobyclemson/Applications/IntelliJ IDEA.app/Contents/MacOS/idea"

diff-args = ["diff",  "$left", "$right"]
edit-args = ["diff",  "$left", "$right"]
merge-args = ["merge" , "$left", "$right", "$base", "$output"]

[merge-tools.pycharm]
program = "/Users/tobyclemson/Applications/PyCharm.app/Contents/MacOS/pycharm"

diff-args = ["diff",  "$left", "$right"]
edit-args = ["diff",  "$left", "$right"]
merge-args = ["merge" , "$left", "$right", "$base", "$output"]

[merge-tools.rustrover]
program = "/Users/tobyclemson/Applications/RustRover.app/Contents/MacOS/rustrover"

diff-args = ["diff",  "$left", "$right"]
edit-args = ["diff",  "$left", "$right"]
merge-args = ["merge" , "$left", "$right", "$base", "$output"]
